/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practica_final;

import java.awt.image.BufferedImage;
import sm.cmr.iu.Lienzo2D;

/**
 * Clase de Ventana Interna Camara que se utilizara para mostrar imágenes
 *
 * @author Cesar Muñoz Reinoso
 */
public final class VentanaInternaImagen extends VentanaInternaSM {

    /**
     * Constructor de Ventana interna imagen vacío
     */
    public VentanaInternaImagen() {
        super();
        initComponents();
    }
    
    /**
     * Constructor de Ventana interna imagen con una imagen
     * @param img
     */
    public VentanaInternaImagen(BufferedImage img) {
        super();
        initComponents();
        this.getLienzo2D().setImagen(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new sm.cmr.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(300, 300));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Devuelve el lienzo de la ventana
     * @return 
     */
    public Lienzo2D getLienzo2D() {
        return lienzo;
    }
    
    /**
     * Establece el lienzo de la ventana 
     * @param lienzo
     */
    public void setLienzo2D(Lienzo2D lienzo) {
        this.lienzo = lienzo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.cmr.iu.Lienzo2D lienzo;
    // End of variables declaration//GEN-END:variables
}
