/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practica_final;

import java.awt.image.BufferedImage;

/**
 * Clase de Ventana Interna de la que heredan todos los tipos de ventana que
 * utlizaremos
 *
 * @author Cesar Muñoz Reinoso
 */
public class VentanaInternaSM extends javax.swing.JInternalFrame {

    /**
     * Constructor de Ventana interna
     */
    public VentanaInternaSM() {
        initComponents();
    }

    /**
     * Devuelve la imagen de la ventana
     *
     * @return
     */
    public BufferedImage getImagen() {
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(100, 36));
        setRequestFocusEnabled(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}